{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.fullname" . }}-config
  labels:
    {{- include "redis.labels" . | nindent 4 }}
data:
  redis.conf: |
    maxmemory {{ .Values.deployment.resources.limits.memory | default "128Mi" | trimSuffix "Mi" }}mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
{{- end }}