apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/component: bootstrap
spec:
  project: default
  source:
    # 자기 자신이 있는 GitOps 리포지토리를 바라봄
    repoURL: 'https://github.com/llokr1/Migration-Test.git'
    # ArgoCD Helm 차트 경로를 지정
    path: 'charts/argo-cd'
    targetRevision: main
    helm:
      # 이 차트의 values.yaml을 사용하도록 명시
      valueFiles:
        - values.yaml
  destination:
    # 배포 목적지는 바로 자기 자신(내부 클러스터)의 argocd 네임스페이스
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 10
