# Default values for auth-service
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
  name: auth-service
  type: ClusterIP
  port: 8081
  targetPort: 8081

deployment:
  replicaCount: 1
  image:
    repository: auth-service
    tag: "31b5ea9"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  env:
    # ============================================================
    # 🔐 PRODUCTION ENVIRONMENT VARIABLES
    # Updated for Production Deployment
    # ============================================================
    
    # Server Configuration
    - name: SERVER_PORT
      value: "8081"
    - name: SPRING_PROFILES_ACTIVE
      value: "prod"
    
    # Spring DataSource Configuration (Spring Boot Standard)
    - name: SPRING_DATASOURCE_URL
      value: "jdbc:postgresql://loventure-auth-service-postgres:5432/auth"
    - name: SPRING_DATASOURCE_USERNAME
      value: "root"
    - name: SPRING_DATASOURCE_PASSWORD
      value: "Enqjrdlemf"
    - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
      value: "org.postgresql.Driver"
    
    # JPA/Hibernate Configuration
    - name: SPRING_JPA_HIBERNATE_DDL_AUTO
      value: "update"
    - name: SPRING_JPA_SHOW_SQL
      value: "true"
    - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
      value: "org.hibernate.dialect.PostgreSQLDialect"
    
    # JWT Configuration
    - name: SPRING_JWT_SECRET
      value: "Z2FjaG9ua2FrYW9lbnRlcnByaXNlc29mdHdhcmVhY2FkZW15c2V2ZW5waXR0ZXJwYXR0ZXJsb3ZlbnR1cmV0d290cmFsbGFsbGVvdHJhbGxhbGxh"
    - name: SPRING_JWT_EXPIRATION
      value: "600000"
    - name: SPRING_JWT_REFRESH_EXPIRATION
      value: "1209600000"
    - name: SPRING_JWT_COOKIE_SECURE
      value: "true"
    - name: SPRING_JWT_COOKIE_DOMAIN
      value: "loventure.us"
    - name: SPRING_JWT_ACCESS_TOKEN_EXPIRE_LENGTH
      value: "600000"
    - name: SPRING_JWT_REFRESH_TOKEN_EXPIRE_LENGTH
      value: "1209600000"
    - name: SPRING_JWT_REDIRECT_ONBOARDING
      value: "https://loventure.us/onboarding"
    - name: SPRING_JWT_REDIRECT_BASE
      value: "https://loventure.us/home"
    - name: SPRING_JWT_REDIRECT_COUPLEROOM
      value: "https://loventure.us/home/coupleroom"
    - name: SPRING_JWT_REDIRECT_HOME
      value: "https://loventure.us/home"
    
    # OAuth2 - Google Configuration
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID
      value: "91503250441-ids1ouvht5df7gipj19e4gk2dljbe9l7.apps.googleusercontent.com"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET
      value: "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"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI
      value: "https://api.loventure.us/login/oauth2/code/google"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE
      value: "authorization_code"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE
      value: "profile,email"
    
    # OAuth2 - Kakao Configuration
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_ID
      value: "d20d5408a3b88f27f63c2a30a5e13f33"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_SECRET
      value: "i9yR1G9I84AnuOW4jpxge9eg9jUU1iFF"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_REDIRECT_URI
      value: "https://api.loventure.us/login/oauth2/code/kakao"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_AUTHORIZATION_GRANT_TYPE
      value: "authorization_code"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT_AUTHENTICATION_METHOD
      value: "client_secret_post"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_SCOPE
      value: "profile_nickname,account_email"
    
    # OAuth2 - Kakao Provider Configuration
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_AUTHORIZATION_URI
      value: "https://kauth.kakao.com/oauth/authorize"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_TOKEN_URI
      value: "https://kauth.kakao.com/oauth/token"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_INFO_URI
      value: "https://kapi.kakao.com/v2/user/me"
    - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KAKAO_USER_NAME_ATTRIBUTE
      value: "id"
    
    # Swagger/OpenAPI Configuration
    - name: SPRINGDOC_SWAGGER_UI_PATH
      value: "/swagger-ui.html"
    - name: SPRINGDOC_API_DOCS_PATH
      value: "/v3/api-docs"
    - name: SPRINGDOC_API_DOCS_ENABLED
      value: "true"
    
    # Management/Actuator Configuration
    - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
      value: "health,info,metrics,prometheus"
    - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
      value: "always"
    - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_COMPONENTS
      value: "always"
    
    # ============================================================
    # END OF PRODUCTION ENVIRONMENT VARIABLES
    # ============================================================

postgres:
  enabled: true
  image:
    registry: docker.io
    repository: postgres
    tag: "14"
  service:
    port: 5432
  persistence:
    enabled: true
    size: 10Gi
    storageClass: ""
    accessMode: ReadWriteOnce
  auth:
    postgresPassword: "Enqjrdlemf"
    database: "auth"
    username: "root"

global:
  imageRegistry: docker.io/pitterpetter
  imagePullPolicy: IfNotPresent
  namespace: loventure-app
  environment: production